### ISSUE TITLE
wonder if it work on a weak and small student network

### ISSUE THREAD

**Issue by pecanjk** [yuanli2333/Teacher-free-Knowledge-Distillation#1]
Distillation by a strong teacher can improve accuracy of a much weak and small student network. But in your paper, the student network structure are strong case. I wonder if the teacher-free KD can work well on a weak and small student network?

**Comment by yuanli2333** [comment]
Yes, it works for both small and large network, like 5-layers plain CNN, we will update some results for small network in the future.
