### ISSUE TITLE
where's the paper?

### ISSUE THREAD

**Issue by vraivon** [yuanli2333/Teacher-free-Knowledge-Distillation#10]
I cannot find Revisiting Knowledge Distillation via Label Smoothing Regularization on arxiv, only Revisit Knowledge Distillation: a Teacher-free Framework. is there some difference between those two papers?

**Comment by yuanli2333** [comment]
Hi, it is the same paper.
We changed title when submit to CVPR, and it will be changed after CVPR2020 paper be available online.

**Comment by vraivon** [comment]
thank you
