### ISSUE TITLE
Resnet architectures is differnet from  the original networks in the paper

### ISSUE THREAD

**Issue by peipei-pig** [yuanli2333/Teacher-free-Knowledge-Distillation#13]

**Comment by yuanli2333** [comment]
Hi, the resent.py is network on CIFAR10 or CIFAR100, which is different with the resent in ImageNet in the first layer, you can check in here:  https://arxiv.org/pdf/1512.03385.pdf
![resnet](https://user-images.githubusercontent.com/33076543/84384685-e9395100-ac20-11ea-9e20-d67c7b5d2a2b.jpg)

**Comment by peipei-pig** [comment]
ok，thanks. I get it.
