### ISSUE TITLE
What is the difference between Born Again Network and your self-training KD method?

### ISSUE THREAD

**Issue by JiyueWang** [yuanli2333/Teacher-free-Knowledge-Distillation#18]

**Comment by yuanli2333** [comment]
Yes, the first teacher-free is the same as BAN, the second one is different.
The analysis on the relationship between LRS and KD can reveal why teaching itself also work.

**Comment by JiyueWang** [comment]
Thanks for your confirmation.  The analysis in Section 2 and 3 is excellent.
